INSERT INTO users (name, age) VALUES ('Sam', 19);
INSERT INTO users (name, age) VALUES ('Allison', 20);
INSERT INTO users (name, age) VALUES ('Dave', 21);
INSERT INTO users (name, age) VALUES ('Greg', 22);
INSERT INTO users (name, age) VALUES ('Bob', 23);
INSERT INTO users (name, age) VALUES ('Lauren', 22);
INSERT INTO users (name, age) VALUES ('Susie', 35);
INSERT INTO users (name, age) VALUES ('Matt', 34);
INSERT INTO users (name, age) VALUES ('Tim', 36);
INSERT INTO users (name, age) VALUES ('Jessie', 35);
INSERT INTO users (name, age) VALUES ('Evelyn', 19);
INSERT INTO users (name, age) VALUES ('James', 17);
INSERT INTO users (name, age) VALUES ('Gerry', 36);
INSERT INTO users (name, age) VALUES ('Emily', 34);
INSERT INTO users (name, age) VALUES ('Sarah', 30);
INSERT INTO users (name, age) VALUES ('Katie', 32);
INSERT INTO users (name, age) VALUES ('Carlin', 34);
INSERT INTO users (name, age) VALUES ('Olivia', 18);
INSERT INTO users (name, age) VALUES ('Owen', 16);
INSERT INTO users (name, age) VALUES ('Ryan', 17);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cataan', 'Boardgame', '1000', '10-1-2020', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Hive', 'Boardgame', '5000', '11-1-2020', '1-1-2021');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('EEW Mini', 'Spinning Tools', '4000', '9-1-2020', '11-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stain Proof Shirt', 'Clothing', '10000', '1-1-2020', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Automatic Bottle Opener', 'Kitchen', '5000', '10-1-2020', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Multi Function Skirt', 'Clothing', '11000', '5-1-2020', '11-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cataan', 'Boardgame', '1000', '10-1-2010', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cataan', 'Boardgame', '1000', '10-1-2010', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cataan', 'Boardgame', '1000', '10-1-2010', '12-1-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cataan', 'Boardgame', '1000', '10-1-2010', '12-1-2020');